#!/bin/bash
# generated by Gemini: 

# --- 1. SYSTEM UPDATES ---
# Ensure the package list is fresh and the system is upgraded
sudo apt update && sudo apt upgrade -y

# --- 2. CORE UTILITIES ---
# Basic tools needed for the rest of the installation
sudo apt install git curl wget tmux ethtool -y

# --- 3. ZSH & OH-MY-ZSH ---
# Install Zsh
sudo apt install zsh -y
# Install Oh My Zsh (Non-interactive install)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
# Change default shell to Zsh
sudo chsh -s $(which zsh) $USER

# --- 4. SSH KEY FOR GITHUB ---
# Generate Ed25519 key (Replace with your email)
ssh-keygen -t ed25519 -C "jxitc@hotmail.com" -f ~/.ssh/id_ed25519 -N ""
echo "--- COPY THIS KEY TO GITHUB ---"
cat ~/.ssh/id_ed25519.pub
echo "-------------------------------"

# --- 6. CLAUDE CODE (NATIVE) ---
# Install the Claude CLI tool
curl -fsSL https://claude.ai/install.sh | bash
# Add local bin to PATH for Zsh
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc

# --- 8. CONFIG REPO ---
# Note: This requires the SSH key to be added to GitHub first
# git clone git@github.com:jxitc/configs.git ~/configs

echo "Setup script finished. Please restart your terminal or run 'zsh'."
